# Generated by Django 4.1.1 on 2022-09-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='location',
        ),
        migrations.AddField(
            model_name='barber',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='barber',
            name='state',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
