# Generated by Django 4.1.1 on 2022-12-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='contact',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='barber',
            name='website',
            field=models.TextField(default='N/A'),
        ),
    ]
