# Generated by Django 4.1.1 on 2022-09-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_project', '0003_alter_barber_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='ratings',
            field=models.CharField(max_length=100),
        ),
    ]
